CREATE DATABASE `QUANLYDUAN` CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `QUANLYDUAN`;

CREATE TABLE `NHANVIEN`
(
    HONV VARCHAR(10) NOT NULL,
    TENLOT VARCHAR(10) NOT NULL,
    TENNV VARCHAR(10) NOT NULL,
    PHAI VARCHAR(5) NOT NULL DEFAULT 'Nam',
    LUONG INT NOT NULL,
    MANV INT PRIMARY KEY NOT NULL,
    NGSINH DATE NOT NULL,
    DIACHI VARCHAR(20) NOT NULL,
    PHG INT NOT NULL
);

CREATE TABLE `DEAN`
(
    TENDA VARCHAR(20) NOT NULL,
    MADA INT PRIMARY KEY NOT NULL,
    DDIEM_DA VARCHAR(20) NOT NULL,
    PHG INT NOT NULL
);

CREATE `PHONGBAN`
(
    PHG INT PRIMARY KEY NOT NULL,
    TENPHG VARCHAR(20)
);

CREATE TABLE `PHANCONG`
(
    MANV INT NOT NULL,
    MADA INT NOT NULL,
    SOGIO FLOAT NOT NULL
);

INSERT INTO `NHANVIEN`
VALUE('Đinh','Lê','Tiên','Nam',4000,123456789,'1965/09/01','Nguyễn Trãi, Q5',1);
INSERT INTO `NHANVIEN`
VALUE('Nguyễn','Thị','Loan','Nữ',2500,333445555,'1955/08/12','Nguyễn Huệ, Q1',5);
INSERT INTO `NHANVIEN`
VALUE('Nguyễn','Lan','Anh','Nữ',4300,666884444,'1962/09/15','Lê Lợi, Q1',5);
INSERT INTO `NHANVIEN`
VALUE('Trần','Thanh','Tâm','Nam',3800,453453453,'1972/07/31','Trần Não, Q2',2);

INSERT INTO `DEAN`
VALUE('Sản phẩm X',1,'Quy Nhơn',5);
INSERT INTO `DEAN`
VALUE('Sản phẩm Y',2,'Nha Trang',5);
INSERT INTO `DEAN`
VALUE('Sản phẩm Z',3,'TP HCM',5);
INSERT INTO `DEAN`
VALUE('Tin học hóa',10,'Bình Dương',4);

/*2 bảng PHONGBAN và PHANCONG INSERT tương tự*/

ALTER TABLE `PHANCONG` ADD CONSTRAINT fk_manv FOREIGN KEY (MANV) REFERENCES `NHANVIEN` (MANV);
ALTER TABLE `PHANCONG` ADD CONSTRAINT fk_maDA FOREIGN KEY (MADA) REFERENCES `DEAN` (MADA);
ALTER TABLE `DEAN` ADD CONSTRAINT fk_phg FOREIGN KEY (PHG) REFERENCES `PHONGBAN` (PHG);

SELECT * FROM `NHANVIEN`;
SELECT * FROM `NHANVIEN` WHERE PHG=5;
SELECT MANV, HONV, TENLOT, TENNV FROM `NHANVIEN` WHERE PHG=5 AND LUONG>=3000
SELECT MANV, TENNV FROM `NHANVIEN` WHERE LUONG BETWEEN 2000 AND 8000;
SELECT * FROM `NHANVIEN` WHERE DIACHI LIKE '%Nguyễn%';
SELECT COUNT(MANV) AS 'Số lượng nhân viên' FROM `NHANVIEN`;

SELECT pb.TENPHG AS 'Tên phòng ban', COUNT(nv.PHG) AS 'Số lượng nhân viên'
FROM `NHANVIEN` nv JOIN `PHONGBAN` pb ON nv.PHG = pb.PHG
GROUP BY TENPHG;

SELECT nv.MANV, nv.TENNV, pb.TENPHG
FROM `NHANVIEN` nv JOIN `PHONGBAN` pb ON nv.PHG = pb.PHG
WHERE pb.TENPHG = 'Kế toán';



